apiVersion: apps/v1
kind: Deployment
metadata:
  name: vue-storefront-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vue-storefront-api
  template:
    metadata:
      labels:
        app: vue-storefront-api
    spec:
      restartPolicy: Always
      containers:
      - name: vue-storefront-api
        image: docker.pkg.github.com/it-jonction/vue-storefront-api/vue-storefront-api:0.0.32
        envFrom:
        - configMapRef:
            name: vue-storefront-api-config
        ports:
        - containerPort: 8080
        volumeMounts:
        - mountPath: /var/www/var
          name: code
        - mountPath: /var/www/dist
          name: dist
      volumes:
      - name: code
        emptyDir:
          medium: Memory
      - name: dist
        emptyDir:
          medium: Memory
      imagePullSecrets:
        - name: regcred
